export const siteConfig = {
  name: "Local AI OS",
  description: "Private knowledge assistant for local infrastructure.",
  defaultLocale: "en",
  shell: {
    eyebrow: "Workspace",
    deploymentTitle: "Local-first deployment",
    deploymentDescription:
      "Windows for development, Ubuntu for production, shared Ollama runtime.",
    closeSidebarLabel: "Collapse sidebar",
    openSidebarLabel: "Expand sidebar",
    systemWarningTitle: "Runtime warning",
    systemWarningOpenSettingsLabel: "Open settings",
    systemWarningFallback: "Could not load runtime diagnostics.",
    recoveryTitle: "Runtime recovered",
    recoveryFallback:
      "Core services are healthy again. Background recovery is available.",
    recoveryNoop: "Core services are healthy again. No incomplete documents needed recovery.",
    recoveryError:
      "Core services are healthy again, but automatic recovery could not complete.",
    recoveryOpenKnowledgeLabel: "Open knowledge",
  },
  navigation: [
    { href: "/chat", label: "Chat" },
    { href: "/knowledge", label: "Knowledge" },
    { href: "/settings", label: "Settings" },
  ],
  dashboard: {
    eyebrow: "Private knowledge assistant",
    title: "Settings",
    subtitle: "System status, runtime overview, and model inventory.",
    cards: {
      backendStatus: "Backend status",
      installedModels: "Installed models",
      uploadedDocuments: "Uploaded documents",
      modelStatus: "Model status",
    },
    modelsTitle: "Available models",
    modelsSubtitle: "Fetched live from Ollama through the backend",
    emptyModels: "No models available",
  },
  chat: {
    title: "Chat",
    subtitle:
      "Ask questions against your local model with saved conversations and document-aware retrieval.",
    sidebarTitle: "Conversations",
    sidebarSubtitle: "Chats",
    sidebarConversationLimit: 10,
    newConversationLabel: "New chat",
    searchConversationPlaceholder: "Search chats...",
    emptyFilteredConversationLabel: "No chats match your search.",
    renameConversationLabel: "Rename",
    renameConversationSaveLabel: "Save",
    renameConversationCancelLabel: "Cancel",
    renameConversationPlaceholder: "Conversation title",
    deleteConversationLabel: "Delete",
    emptyConversationLabel: "No saved conversations yet.",
    loadingConversationsLabel: "Loading conversations...",
    showMoreConversationsLabel: "Show more",
    showLessConversationsLabel: "Show less",
    clearLabel: "Clear",
    sendLabel: "Send",
    messagesLabel: "messages",
    inputPlaceholder: "Ask about your local knowledge...",
    loadingLabel: "Thinking...",
    modelLoadingLabel: "Loading models...",
    modelLoadError: "Could not load models from the backend.",
    modelEmptyLabel: "No models available",
    noChatModelsLabel: "No chat-capable models available",
    scopeLabel: "Document scope",
    scopeAllLabel: "All documents",
    scopeButtonLabel: "Choose documents",
    scopeEmptyLabel: "No processed documents available yet",
    scopeSelectedSuffix: "docs",
    scopeResetLabel: "Use all",
    scopeHelper:
      "Limit retrieval to specific processed documents when you want tighter answers.",
    composerHint: "Enter to send. Shift+Enter for a new line.",
    initialAssistantMessage: "Welcome to Local AI OS.",
    clearedAssistantMessage: "Chat cleared.",
    labels: {
      user: "You",
      assistant: "Assistant",
    },
    retrievalTitle: "Retrieval",
    retrievalGroundedLabel: "Grounded",
    retrievalLabels: {
      returned: "Returned",
      semantic: "Semantic",
      term: "Term",
      scoped: "Scoped",
      metadata: "Metadata",
      confidence: "Confidence",
      topScore: "Top score",
    },
    retrievalModeLabels: {
      none: "None",
      hybrid: "Hybrid",
      semantic: "Semantic",
      term: "Term",
    },
    retrievalConfidenceLabels: {
      low: "Low",
      medium: "Medium",
      high: "High",
    },
    retrievalConfidenceDescriptions: {
      low: "This answer is based on weak or limited retrieval. It may still be useful, but it is worth double-checking the cited passages.",
      medium:
        "The supporting passages look reasonably relevant, but there is still some ambiguity in the retrieval.",
      high: "The top supporting passages look strong and closely aligned with the question.",
    },
    sourcesTitle: "Sources",
    sourceOpenLabel: "Open source",
    sourceScoreLabel: "Score",
    sourceOcrLabel: "OCR",
    sourceOcrHint:
      "This source was read through OCR. Minor word errors are still possible in scanned or handwritten text.",
    retrievalHint: "Processed local documents are used as context when relevant.",
    errors: {
      backendUnavailable: "Error reaching backend.",
      conversationLoadError: "Could not load conversations.",
      conversationUpdateError: "Could not rename conversation.",
      conversationDeleteError: "Could not delete conversation.",
    },
  },
  knowledge: {
    title: "Knowledge",
    subtitle:
      "Upload internal documents and manage the files available for the next retrieval layer.",
    manageConnectorsLink: "Manage connectors in Settings",
    totalFilesButton: "{count} files",
    fileTypesModalTitle: "Stored file types",
    fileTypesModalSubtitle:
      "A quick overview of which file formats are currently stored in Knowledge.",
    fileTypesModalClose: "Close",
    fileTypesTypeLabel: "Type",
    fileTypesCountLabel: "Files",
    fileTypesEmptyState: "No stored files yet.",
    uploadTitle: "Upload documents",
    uploadSubtitle:
      "Store PDFs, Word files, spreadsheets, slide decks, images, notes, data files, code, and config files locally so the knowledge layer can use them in future RAG flows.",
    uploadButton: "Upload files",
    uploadingButton: "Uploading...",
    selectedFilesLabel: "Selected files",
    searchPlaceholder: "Search files...",
    previewButton: "Preview",
    previewTitle: "Document preview",
    previewCloseLabel: "Close",
    previewUseInChatLabel: "Use in chat",
    previewFocusedChunkLabel: "Matched chunk",
    previewLoadingLabel: "Loading preview...",
    previewTextTitle: "Extracted text",
    previewChunksTitle: "Chunks",
    previewSignalsTitle: "Detected signals",
    previewTruncatedLabel: "Truncated",
    previewEmptyText: "No extracted text is available for this document yet.",
    previewEmptyChunks: "No chunks are available for this document yet.",
    previewEmptySignals: "No document signals are available for this document yet.",
    previewMeta: {
      type: "Type",
      detectedType: "Detected type",
      documentDate: "Document date",
      entities: "Detected company",
      size: "Size",
      ocr: "OCR",
      characters: "Characters",
      chunks: "Chunks",
    },
    sortLabel: "Sort",
    sortNewestLabel: "Newest first",
    sortOldestLabel: "Oldest first",
    sortNameLabel: "Name A-Z",
    sortLargestLabel: "Largest first",
    sortDocumentDateNewestLabel: "Document date newest",
    sortDocumentDateOldestLabel: "Document date oldest",
    typeFilterLabel: "Document type",
    sourceFilterLabel: "Source",
    visibleCountLabel: "Showing {visible} of {total} documents",
    serverWindowLabel: "Loaded {loaded} of {total} from the server",
    showMoreButton: "Show 50 more",
    showLessButton: "Show fewer",
    filterAllTypesLabel: "All document types",
    filterAllSourcesLabel: "All sources",
    filterAllLabel: "All statuses",
    filterProcessedLabel: "Processed",
    filterPendingLabel: "Pending",
    filterFailedLabel: "Failed",
    filterIndexFailedLabel: "Index failed",
    unknownTypeLabel: "General document",
    noDocumentDateLabel: "No date detected",
    noDocumentEntitiesLabel: "No company detected",
    emptyFilteredState: "No documents match the current filter.",
    refreshButton: "Refresh",
    retryIncompleteButton: "Retry failed indexing",
    retryingIncompleteButton: "Retrying...",
    reprocessAllButton: "Reprocess all",
    reprocessingAllButton: "Queueing all...",
    activeProcessingNotice:
      "Document processing is active. This page refreshes automatically while files are being prepared.",
    emptyState: "No documents uploaded yet.",
    listTitle: "Stored documents",
    deleteButton: "Delete",
    reprocessButton: "Reprocess",
    hideButton: "Hide",
    unhideButton: "Unhide",
    restrictButton: "Restrict",
    editRestrictedAccessButton: "Edit access",
    standardAccessButton: "Standard access",
    restrictPrompt:
      "Allowed usernames for this restricted document, comma separated:",
    restrictPromptEmpty:
      "Enter at least one enabled username to restrict a document.",
    processingButton: "Processing...",
    hiddenVisibilityLabel: "Hidden",
    restrictedVisibilityLabel: "Restricted",
    processedLabel: "Processed",
    pendingLabel: "Pending",
    failedLabel: "Failed",
    indexedLabel: "Indexed",
    indexingPendingLabel: "Index pending",
    indexingFailedLabel: "Index failed",
    stageQueuedLabel: "Queued",
    stageExtractingLabel: "Extracting text",
    stageChunkingLabel: "Preparing chunks",
    stageIndexingLabel: "Building index",
    stageCompletedLabel: "Completed",
    stageFailedLabel: "Failed",
    ocrUsedLabel: "OCR used",
    ocrNotNeededLabel: "Native text",
    ocrUnavailableLabel: "OCR unavailable",
    ocrFailedLabel: "OCR failed",
    elapsedLabel: "Elapsed:",
    longRunningHint:
      "This is taking longer than usual. Large PDFs, scanned pages, or handwriting can slow processing down.",
    noTextHint:
      "No readable text was extracted. This usually means the PDF is scanned or handwritten and needs OCR.",
    ocrUnavailableHint:
      "OCR fallback is not available yet in this runtime. Install and configure OCR support, then reprocess the document.",
    ocrFailedHint:
      "OCR was attempted but did not produce enough readable text. Handwriting and low-quality scans can still be difficult.",
    columns: {
      name: "Name",
      type: "Type",
      size: "Size",
      status: "Status",
      chunks: "Chunks",
      documentDate: "Document date",
      uploadedAt: "Uploaded",
      actions: "Actions",
    },
    messages: {
      uploadSuccess: "Document uploaded.",
      uploadSuccessPlural: "files uploaded.",
      uploadQueued: "Document uploaded and queued for processing.",
      uploadQueuedPlural: "files uploaded and queued for processing.",
      uploadError: "Could not upload document.",
      deleteError: "Could not delete document.",
      processQueued: "Document queued for reprocessing.",
      processError: "Could not process document.",
      reprocessAllQueued: "All documents queued for reprocessing.",
      reprocessAllNoop: "No documents were available to reprocess.",
      reprocessAllError: "Could not reprocess all documents.",
      retryIncompleteSuccess: "Incomplete indexing retried.",
      retryIncompleteNoop: "No incomplete documents to retry.",
      retryIncompleteError: "Could not retry incomplete indexing.",
      recoverSuccess: "Runtime recovery retried incomplete indexing.",
      recoverNoop: "Runtime recovered. No incomplete indexing needed a retry.",
      recoverError: "Runtime recovered, but automatic retry did not complete.",
      previewError: "Could not load document preview.",
      loadError: "Could not load documents.",
      noFileSelected: "Select a file before uploading.",
      hideSuccess: "Document hidden from non-admin views.",
      unhideSuccess: "Document restored to standard visibility.",
      restrictSuccess: "Document access limited to selected users.",
      visibilityError: "Could not update document visibility.",
    },
  },
  connectors: {
    title: "Connectors",
    subtitle:
      "Connect external sources and sync them into the same knowledge pipeline.",
    refreshButton: "Refresh connectors",
    createTitle: "Add connector",
    createSubtitle:
      "Start narrow so first sync stays fast and predictable.",
    createButton: "Create connector",
    creatingButton: "Creating...",
    savedTitle: "Saved connectors",
    savedSubtitle:
      "Run sync manually for now.",
    setupTitle: "Setup choices",
    setupDescription:
      "Smaller, text-heavy scope is usually the best first sync.",
    loadingLabel: "Loading connectors...",
    refreshingLabel: "Refreshing saved connectors...",
    emptyState: "No connectors created yet.",
    syncButton: "Sync now",
    syncingButton: "Syncing...",
    previewSyncButton: "Preview sync",
    previewingSyncButton: "Previewing...",
    browseFoldersButton: "Browse folders",
    browsingFoldersButton: "Loading folders...",
    editButton: "Edit",
    saveButton: "Save",
    savingButton: "Saving...",
    cancelButton: "Cancel",
    deleteButton: "Delete",
    deletingButton: "Deleting...",
    disableButton: "Disable",
    enableButton: "Enable",
    neverSyncedLabel: "Not synced yet",
    authModeLabel: "Auth mode",
    lastSyncLabel: "Last sync",
    containerLabel: "Container",
    rootPathLabel: "Root path",
    folderIdLabel: "Folder ID",
    driveIdLabel: "Drive ID",
    maxFilesLabel: "Max files per sync",
    documentVisibilityLabel: "Default access",
    accessUsersLabel: "Allowed users",
    enabledLabel: "Enabled",
    disabledLabel: "Disabled",
    syncSummaryTitle: "Latest sync",
    syncSummaryScannedLabel: "Scanned",
    syncSummaryImportedLabel: "Imported",
    syncSummaryUpdatedLabel: "Updated",
    syncSummarySkippedLabel: "Skipped",
    syncResultsTitle: "Recent sync results",
    syncResultsEmpty: "No files were returned in the latest sync result.",
    previewBadge: "Preview",
    folderPickerTitle: "Available folders",
    folderPickerEmpty: "No folders found for the current connector settings.",
    folderPickerPick: "Use this folder",
    folderPickerSelectedPrefix: "Selected folder",
    deleteConfirm:
      "Delete this connector? Imported documents stay in Knowledge until removed separately.",
    folderIdPlaceholder: "Optional Google folder ID",
    driveIdPlaceholder: "Optional shared drive ID",
    maxFilesPlaceholder: "Optional cap, for example 25",
    accessUsersPlaceholder: "Comma separated usernames for restricted sources",
    notesPlaceholder:
      "Example: pilot sync limited to office, pdf, code, and text files.",
    accessUsersHelp:
      "Restricted sources are visible only to admin and the usernames listed here.",
    accessUsersDisabledHelp:
      "Allowed users only apply when the connector default access is set to Restricted.",
    availableUsersLabel: "Enabled users",
    patternsHint:
      "New connectors start with text-like, Office, code/config, and PDF patterns. Images and zip files are excluded.",
    documentVisibilityOptions: {
      standard: "Standard",
      hidden: "Hidden",
      restricted: "Restricted",
    },
    presetLabel: "Sync scope",
    presetRecommended: "Recommended",
    presetOfficeOnly: "Office + PDF",
    presetCodeAndText: "Code + text",
    presetAllTextLike: "All text-like",
    presetHelpRecommended:
      "Best default for most teams: office docs, PDFs, notes, data files, and common code/config files.",
    presetHelpOfficeOnly:
      "Safer first sync focused on Office files and PDFs.",
    presetHelpCodeAndText:
      "Good for engineering-heavy folders with scripts, configs, markdown, and text files.",
    presetHelpAllTextLike:
      "Broadest preset. Includes all supported text-like, office, and code/config formats while still skipping images and archives.",
    fields: {
      name: "Name",
      provider: "Provider",
      authMode: "Auth mode",
      rootPath: "Root path",
      container: "Container label",
      documentVisibility: "Default document access",
      accessUsers: "Allowed users",
      folderId: "Folder ID",
      driveId: "Drive ID",
      maxFiles: "Max files per sync",
      notes: "Notes",
    },
    messages: {
      loadError: "Could not load connectors.",
      createSuccess: "Connector created.",
      createError: "Could not create connector.",
      updateSuccess: "Connector updated.",
      updateError: "Could not update connector.",
      deleteSuccess: "Connector deleted.",
      deleteError: "Could not delete connector.",
      browseError: "Could not browse folders.",
      syncSuccessPrefix: "Connector sync finished.",
      syncError: "Could not sync connector.",
    },
  },
  settings: {
    auth: {
      title: "Admin access",
      subtitle:
        "Settings and connector management are protected here. Sign in with a local admin account to continue.",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter password",
      loginButton: "Unlock settings",
      loggingInButton: "Unlocking...",
      logoutButton: "Lock settings",
      safeModeBadge: "Safe mode",
      unlockedBadge: "Admin unlocked",
      loginError: "Could not unlock settings.",
      configurationWarning:
        "Admin auth is enabled but not fully configured. Add ADMIN_PASSWORD_HASH and ADMIN_SESSION_SECRET.",
      lockHelp:
        "Lock settings only signs out the current admin session.",
      envToggleHelp:
        "To disable admin auth, set AUTH_ENABLED=false in .env and restart. To disable safe mode, set SAFE_MODE=false and restart.",
    },
    tabs: {
      overview: "Overview",
      documents: "Documents",
      storage: "Storage",
      cleanup: "Cleanup",
      runtime: "Runtime",
      retrieval: "Retrieval",
      connectors: "Connectors",
      users: "Users",
      security: "Security",
      audit: "Audit",
      backups: "Backups",
      logs: "Logs",
      models: "Models",
    },
    securityTitle: "Security",
    securitySubtitle:
      "Current protection state and the next layer of access control for sensitive workspaces.",
    securityCards: {
      adminAuth: "Admin auth",
      safeMode: "Safe mode",
      protectedAreas: "Protected areas",
      futureControls: "Next controls",
      howItWorks: "How it works",
      auditTrail: "Audit trail",
    },
    securityValues: {
      enabled: "Enabled",
      disabled: "Disabled",
      configured: "Configured",
      notConfigured: "Not configured",
      unlocked: "Unlocked",
      locked: "Locked",
    },
    securityProtectedAreas: [
      "Settings changes",
      "Connector creation, sync, and import controls",
      "Logs",
      "Cleanup",
      "Backup import/export",
    ],
    securityFutureControls: [
      "Hide or pin sensitive documents",
      "Richer document and source permissions",
      "Per-source and per-document permissions",
      "Audit trails for account and permission changes",
    ],
    securityNotes: {
      authDisabled:
        "Admin auth is off in this environment. Fine for local prototyping, but not for wider internal use.",
      authEnabledConfigured:
        "Admin auth is active and configured. Sensitive surfaces now require an admin unlock, and repeated failed sign-ins trigger a temporary lockout.",
      authEnabledNotConfigured:
        "Admin auth is on but not fully configured yet. Add ADMIN_PASSWORD_HASH and ADMIN_SESSION_SECRET before relying on it.",
      safeModeEnabled:
        "Safe mode is active. Higher-risk actions like connector sync, cleanup, and backup import/export are blocked.",
      safeModeDisabled:
        "Safe mode is off. Better for normal setup and iteration, but higher-risk admin actions remain available.",
    },
    securityAuditTitle: "Recent audit activity",
    securityAuditSubtitle:
      "Track logins, user changes, permission changes, connector actions, and other sensitive events.",
    securityAuditRefreshLabel: "Refresh audit",
    securityAuditOpenLogsLabel: "Open full logs",
    securityAuditEmpty: "No audit events recorded yet.",
    securityAuditLoadError: "Could not load audit events.",
    runtimeTitle: "Runtime configuration",
    runtimeSubtitle:
      "Update the local AI runtime without editing environment files by hand.",
    overviewTitle: "System overview",
    overviewSubtitle:
      "Current backend health, dependency reachability, and storage readiness.",
    overviewCards: {
      overallStatus: "Overall status",
      conversations: "Saved chats",
      processedDocuments: "Processed docs",
      indexedDocuments: "Indexed docs",
      failedDocuments: "Failed docs",
      totalLocalStorage: "Total local storage",
      documentFamilies: "Document families",
      versionedDocuments: "Versioned docs",
      topicReadyDocuments: "Tagged docs",
      maintenanceBacklog: "Pending enrichment",
    },
    documentsTitle: "Document intelligence",
    documentsSubtitle:
      "See family grouping, version readiness, topic coverage, and idle enrichment state.",
    documentsControls: {
      refreshButton: "Run one maintenance step",
      refreshingButton: "Refreshing...",
      refreshSuccess: "Document intelligence refreshed.",
      refreshNoop: "No pending document intelligence work was found.",
      refreshError: "Could not refresh document intelligence.",
      familiesTitle: "Top document families",
      staleTitle: "Pending intelligence",
      maintenanceTitle: "Idle maintenance",
      emptyFamilies: "No document families have been detected yet.",
      emptyStale: "No documents are waiting for intelligence backfill.",
    },
    dependenciesTitle: "Dependencies",
    dependenciesSubtitle:
      "Live reachability and runtime details for core dependencies.",
    storageTitle: "Storage",
    storageSubtitle:
      "Current local content volume across documents, indexing, and saved conversations.",
    storageUsageTitle: "Storage usage",
    storageUsageSubtitle:
      "See what is taking space locally.",
    storageControls: {
      sortLabel: "Sort",
      filterLabel: "Filter",
      sortLargest: "Largest first",
      sortSmallest: "Smallest first",
      sortName: "Name A-Z",
      filterAll: "All areas",
      filterCleanable: "Cleanable only",
      filterPersistent: "Persistent only",
      empty: "No storage areas match the current filter.",
      cleanLabel: "Clean",
      cleanAllLabel: "Clean safe areas",
      cleaningLabel: "Cleaning...",
      cleanupHint:
        "Only safe-to-regenerate areas can be cleaned here. Persistent uploads, vectors, and chats stay untouched.",
      cleanupError: "Could not run cleanup.",
      cleanupConfirmSingle:
        "Clean this safe-to-regenerate storage area? Persistent data will be preserved.",
      cleanupConfirmAll:
        "Clean all safe-to-regenerate storage areas? Persistent data will be preserved.",
    },
    dependencyLabels: {
      ollama: "Ollama",
      qdrant: "Qdrant",
      url: "URL",
      detail: "Detail",
      models: "Models",
      collection: "Collection",
      indexedPoints: "Indexed points",
    },
    statusLabels: {
      ok: "Healthy",
      degraded: "Degraded",
      error: "Offline",
      unknown: "Unknown",
      ready: "Ready",
      missing: "Missing",
      cleanable: "Cleanable",
      persistent: "Persistent",
    },
    toolsTitle: "Debug tools",
    toolsSubtitle:
      "Inspect backend activity and recent application events.",
    openLogsLabel: "Open logs",
    exportTitle: "Backup and export",
    exportSubtitle:
      "Download a portable snapshot of runtime settings, document metadata, and saved chats.",
    exportButton: "Download backup",
    exportingButton: "Preparing backup...",
    exportError: "Could not export backup.",
    importTitle: "Restore backup",
    importSubtitle:
      "Restore runtime settings and saved chats from a previous backup export.",
    importButton: "Import backup",
    importingButton: "Importing...",
    importFileButton: "Choose backup file",
    importNoFileLabel: "No backup file selected.",
    importError: "Could not import backup.",
    importSuccess:
      "Backup imported. Runtime settings and conversations were restored.",
    importWarning:
      "This restores runtime settings and saved chats only. Uploaded files and vector data are not restored here.",
    fields: {
      ollamaBaseUrl: "Ollama base URL",
      defaultModel: "Default chat model",
      embedModel: "Embedding model",
      qdrantUrl: "Qdrant URL",
      retrievalLimit: "Retrieval limit",
      retrievalMinScore: "Minimum retrieval score",
      chunkSize: "Chunk size",
      chunkOverlap: "Chunk overlap",
    },
    saveButton: "Save settings",
    savingButton: "Saving...",
    savedMessage: "Runtime settings saved.",
    loadError: "Could not load runtime settings.",
    saveError: "Could not save runtime settings.",
    statusLoadError: "Could not load system diagnostics.",
    helperText:
      "Changes apply to new requests. Retrieval and indexing settings affect the next processing run.",
  },
  logs: {
    title: "Logs",
    subtitle:
      "Recent backend events, request outcomes, and raw log lines.",
    refreshButton: "Refresh",
    downloadButton: "Download logs",
    eventsTitle: "Recent events",
    rawTitle: "Raw backend log",
    emptyEvents: "No events logged yet.",
    emptyRaw: "No backend log lines yet.",
    loadError: "Could not load logs.",
    filtersTitle: "Filters",
    filterSearchLabel: "Search",
    filterSearchPlaceholder: "Filter by message, event type, or details...",
    filterStatusLabel: "Status",
    filterStatusAll: "All statuses",
    filterTypeLabel: "Type",
    filterTypeAll: "All event types",
    columns: {
      timestamp: "Timestamp",
      actor: "Actor",
      type: "Type",
      status: "Status",
      message: "Message",
      details: "Details",
    },
  },
} as const;
